[Rspec課題4]システムコード修正
yohei-kanno/rspec_app_exam pull request #1
Opened 2021-01-16 02:14 UTC by yohei-kanno

お疲れ様です。

タスクシステムコードの修正を行いましたのでご確認お願いします。

## 概要
システムコードの修正

## 方法 
gemはvernder/bandle以下でインストールを行い
.gitignoreに追記しました。
</br>
save_and_open_page
を活用する為、
```ruby
gem 'launchy'
```
をインストールしております。
</br>
```ruby
config.filter_run :focus
```
特定のテストを実行出来る様にする為の設定を追加しております。
</br>
その上でテストコードの修正を行い下記の通りとなりました。

[![Image from Gyazo](https://i.gyazo.com/ac086ed9301842f9b193cc75e4155195.jpg)](https://gyazo.com/ac086ed9301842f9b193cc75e4155195)

こちらはマージして宜しいでしょうか。
ご確認お願いします。

2021-01-16 04:08 UTC, yuji91 requested changes

2021-01-16 04:08 UTC, yuji91 commented on spec/factories/tasks.rb
> +      status { "done" }
シンボル形式で定義してください。String型でないことが明示できます。
```suggestion
      status { :done }
```

2021-01-16 04:08 UTC, yuji91 commented on spec/spec_helper.rb
> +  # config.filter_run :focus
コメントを追加する必要はないと思います。

2021-01-16 04:08 UTC, yuji91 commented on spec/system/task_spec.rb
> +        #この表記で最後に指定したタブを指定する
コメントはスペースを開けた方が見やすいですね。
```suggestion
        # この表記で最後に指定したタブを指定する
```

2021-01-16 04:08 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
失敗例のPullRequestは確認されましたか？
この修正でどんな問題点があるのか考えてみてください。

2021-01-16 04:08 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to match(task.title)
こちらはどのような問題があって、どのように修正したのか説明できますか？

2021-01-16 04:08 UTC, yuji91 commented on Gemfile.lock
> +  launchy
`save_and_open_page`を実行しなくても、SystemSpecであればテスト失敗時にスクリーンショットは保存されますし、起動するドライバをHeadlessChromeから外すことでブラウザを表示してテストが実行できます。

そのため、特にこのgemを導入する必要はないと思いました。

2021-01-16 05:40 UTC, yohei-kanno commented on spec/factories/tasks.rb
> +    title  { 'Task' }
08beee7 余分なスペースを削除しました。

2021-01-16 05:41 UTC, yohei-kanno commented on spec/factories/tasks.rb
> +      status { "done" }
ea222d0　シンボルにて定義しました。
以前も指摘してもらった事なので意識します。　

2021-01-16 05:42 UTC, yohei-kanno commented on spec/spec_helper.rb
> +  # config.filter_run :focus
3169d54　不要なコメントを削除しました。

2021-01-16 05:43 UTC, yohei-kanno commented on spec/system/task_spec.rb
> +        #この表記で最後に指定したタブを指定する
8963e3f　コメントの後にスペースを追加しました。
また他にも同様のケースがありましたので修正しました。

2021-01-16 05:44 UTC, yohei-kanno commented on Gemfile.lock
> +  launchy
182f1bd　１回も使わなかったのに何故かインストールしてしまいました。
ご指摘の通りですので削除しました。

2021-01-16 05:45 UTC, yohei-kanno commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
22f29bf　viewで使用するメソッドを定義しました。
またメソッドを使用出来る様に設定を追加しました。

2021-01-16 05:54 UTC, yohei-kanno commented on spec/system/task_spec.rb
> +        expect(page).not_to match(task.title)
b457b95
上記修正しました。
最初はタイトルと表示が被っているので書き直しをしていたのでですが、
いつの間にか
『被っていないこと』
を目的としてテストを作成していました。
matchの使い方も理解していないので使用してテストが通ったのでOKと思ってしまったので
matchの使い方は勉強します。

ここでのテストの目的は
『削除したタスクのタイトルが表示されていないこと』
でした。

ですのでクラスネームで範囲を絞り込んでテストを書き換えました。

2021-01-16 06:57 UTC, yuji91 requested changes
あと1点修正をお願いします！

2021-01-16 06:57 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task){ create(:task, project: project) }
Factoryにassociationを定義することでprojectの指定が不要となります。
```suggestion
  let(:task){ create(:task) }
```

2021-01-17 02:37 UTC, yohei-kanno commented on spec/system/task_spec.rb
> +  let(:task){ create(:task, project: project) }
978edc0  Factroryにassosiationを定義しましt

2021-01-17 03:01 UTC, yuji91 requested changes
追加で確認をお願いします。

2021-01-17 03:01 UTC, yuji91 commented on spec/system/task_spec.rb
> +    let(:task_done){ create(:task, :done, project: project) }
associationの定義により、この部分もprojectの記載が不要になると思います。
他のletについても確認してみてください。
```suggestion
    let(:task_done){ create(:task, :done) }
```

2021-01-17 03:42 UTC, yohei-kanno commented on spec/system/task_spec.rb
> +    let(:task_done){ create(:task, :done, project: project) }
7281992
上記修正しましt

2021-01-17 05:01 UTC, yuji91 approved these changes
LGTMです！

2021-01-17 05:41 UTC, merged